name: Lint

on: [ push ]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    node-version: '20'
                    cache: 'npm'

            -   name: Install NPM dependencies
                run: npm ci

            -   name: Run lint
                run: npm run lint
